#!/bin/bash

export CUDA_VISIBLE_DEVICES=$((${SLURM_LOCALID}%${SLURM_GPUS_ON_NODE}))

echo "TASK:${SLURM_PROCID} (locally ${SLURM_LOCALID} on $(hostname)) see GPU ID ${SLURM_STEP_GPUS} on the node, selecting GPU ID ${CUDA_VISIBLE_DEVICES}"

exec $*
